### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/dbt-ext#70]
```[tasklist]
### Tasks
- [x] Set up trusted publisher on PyPI
- [x] Set up `pypi` environment in this GitHub repo, with some permissions
- [x] Use VCS versioning: https://github.com/meltano/dbt-ext/pull/68
- [x] Add a build + release workflow: https://github.com/meltano/dbt-ext/pull/71
- [x] Publish: https://pypi.org/project/meltano-dbt-ext/0.3.0/
- [x] Update the Hub: https://github.com/meltano/hub/pull/1815
```

**Comment by edgarrmondragon** [comment]
First part is done:

<img width="749" alt="Screenshot 2024-07-31 at 5 51 29 p m" src="https://github.com/user-attachments/assets/ec236fac-ab93-4c33-89ef-39221d11e656">

(excuse the Spanglish UI)

**Comment by edgarrmondragon** [comment]
<img width="799" alt="Screenshot 2024-07-31 at 5 54 33 p m" src="https://github.com/user-attachments/assets/0800b72d-2158-425c-bbfd-2d60ffbd6aed">

**Comment by edgarrmondragon** [comment]
PyPI doesn't like our package name:

```
* `invalid-payload`: The name 'dbt-ext' is too similar to an existing project. See https://pypi.org/help/#project-name for more information.
```

https://github.com/meltano/dbt-ext/actions/runs/10201267503/job/28222731657

It probably thinks we're trying to typo-squat some other dbt-related package 😅.

Opinions on renaming the package `meltano-dbt-ext`? The repo would keep the same name, so git refs in any `pip_url` would continue working, but when we switch them to use the package name it'd be `meltano-dbt-ext` instead of `dbt-ext`.

We could also open an issue in https://github.com/pypi/support, but that seems to be too slow of a process and I don't think we're married to `dbt-ext` as the PyPI package name.

Thoughts @meltano/engineering?

**Comment by WillDaSilva** [comment]
That's mildly frustrating, but also a natural consequence of there being a shared global namespace on PyPI.

I support renaming the package to `meltano-dbt-ext`. Normally for something like this I'd recommend a major version bump just to be safe, but in this case we're still using version `0` as the major version, wherein breaking changes are permitted, so it doesn't really matter.

**Comment by edgarrmondragon** [comment]
PR to rename the package: https://github.com/meltano/dbt-ext/pull/73

**Comment by edgarrmondragon** [comment]
All done here
